apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: floppy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPO-URL
    targetRevision: HEAD
    path: flappyapp/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
