apiVersion: apps/v1
kind: Deployment
metadata:
  name: flappy-app-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flappy-app
  template:
    metadata:
      labels:
        app: flappy-app
    spec:
      containers:
        - name: flappy-app
          image: flappyacr777.azurecr.io/flask-app:latest  # Image from ACR
          ports:
            - containerPort: 3000  # Port exposed in the container
