apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traffic-split-route
spec:
  parentRefs:
  - name: gateway-01
    kind: Gateway
    group: gateway.networking.k8s.io
  rules:
  - backendRefs:
    - name: flappy-app-service
      kind: Service
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
