apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flappyhttp
spec:
  parentRefs:
  - kind: Gateway
    name: prod-web
  rules:
  - backendRefs:
    - name: flappy-app-service
      port: 80