apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-argocd-route
  namespace: argocd 
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: default  
  to:
  - group: ""  
    kind: Service
    name: argocd-server  

---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-monitoring-route
  namespace: monitoring 
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: default  
  to:
  - group: ""  
    kind: Service
    name: prom-grafana
